export const COUNTRY_LIST = {
  "AED": "Dirham dos Emirados Árabes Unidos",
  "AFN": "Afegane afegão",
  "XCD": "Dólar do Caribe Oriental",
  "ALL": "Lek albanês",
  "AMD": "Dram armênio",
  "ANG": "Florim das Antilhas Holandesas",
  "AOA": "Kwanza angolano",
  "AQD": "Dólar da Antártida",
  "ARS": "Peso argentino",
  "AUD": "Dólar australiano",
  "AZN": "Manat azeri",
  "BAM": "Marco bósnio-herzegovino",
  "BBD": "Dólar de Barbados",
  "BDT": "Taka de Bangladesh",
  "XOF": "Franco CFA da África Ocidental",
  "BGN": "Lev búlgaro",
  "BHD": "Dinar bareinita",
  "BIF": "Franco burundiano",
  "BMD": "Dólar das Bermudas",
  "BND": "Dólar de Brunei",
  "BOB": "Boliviano",
  "BRL": "Real brasileiro",
  "BSD": "Dólar das Bahamas",
  "NOK": "Coroa norueguesa",
  "BWP": "Pula de Botswana",
  "BYR": "Rublo bielorrusso (descontinuado)",
  "BZD": "Dólar de Belize",
  "CAD": "Dólar canadense",
  "CDF": "Franco congolês",
  "XAF": "Franco CFA da África Central",
  "CHF": "Franco suíço",
  "CLP": "Peso chileno",
  "CNY": "Yuan chinês",
  "COP": "Peso colombiano",
  "CRC": "Colón costarriquenho",
  "CUP": "Peso cubano",
  "CVE": "Escudo cabo-verdiano",
  "CYP": "Libra cipriota (descontinuada)",
  "CZK": "Coroa checa",
  "DJF": "Franco djibutiense",
  "DKK": "Coroa dinamarquesa",
  "DOP": "Peso dominicano",
  "DZD": "Dinar argelino",
  "ECS": "Sucre equatoriano (descontinuado)",
  "EEK": "Coroa estoniana (descontinuada)",
  "EGP": "Libra egípcia",
  "ETB": "Birr etíope",
  "EUR": "Euro",
  "FJD": "Dólar de Fiji",
  "FKP": "Libra das Malvinas",
  "GBP": "Libra esterlina",
  "GEL": "Lari georgiano",
  "GGP": "Libra de Guernsey",
  "GHS": "Cedi ganês",
  "GIP": "Libra de Gibraltar",
  "GMD": "Dalasi gambiano",
  "GNF": "Franco guineense",
  "GTQ": "Quetzal guatemalteco",
  "GYD": "Dólar da Guiana",
  "HKD": "Dólar de Hong Kong",
  "HNL": "Lempira hondurenha",
  "HRK": "Kuna croata",
  "HTG": "Gourde haitiano",
  "HUF": "Forint húngaro",
  "IDR": "Rupia indonésia",
  "ILS": "Novo shekel israelense",
  "INR": "Rupia indiana",
  "IQD": "Dinar iraquiano",
  "IRR": "Rial iraniano",
  "ISK": "Coroa islandesa",
  "JMD": "Dólar jamaicano",
  "JOD": "Dinar jordaniano",
  "JPY": "Iene japonês",
  "KES": "Xelim queniano",
  "KGS": "Som quirguiz",
  "KHR": "Riel cambojano",
  "KMF": "Franco comorense",
  "KPW": "Won norte-coreano",
  "KRW": "Won sul-coreano",
  "KWD": "Dinar kuwaitiano",
  "KYD": "Dólar das Ilhas Caimão",
  "KZT": "Tenge cazaque",
  "LAK": "Kip laosiano",
  "LBP": "Libra libanesa",
  "LKR": "Rupia do Sri Lanka",
  "LRD": "Dólar liberiano",
  "LSL": "Loti do Lesoto",
  "LTL": "Litas lituano (descontinuado)",
  "LVL": "Lat letão (descontinuado)",
  "LYD": "Dinar líbio",
  "MAD": "Dirham marroquino",
  "MDL": "Leu moldavo",
  "MGA": "Ariary malgaxe",
  "MKD": "Dinar macedônio",
  "MMK": "Quiate birmanês",
  "MNT": "Tugrik mongol",
  "MOP": "Pataca de Macau",
  "MRO": "Ouguiya mauritana",
  "MTL": "Lira maltesa (descontinuada)",
  "MUR": "Rupia de Maurício",
  "MVR": "Rupia das Maldivas",
  "MWK": "Kwacha malauiano",
  "MXN": "Peso mexicano",
  "MYR": "Ringgit malaio",
  "MZN": "Metical moçambicano",
  "NAD": "Dólar namibiano",
  "XPF": "Franco CFP",
  "NGN": "Naira nigeriana",
  "NIO": "Córdoba nicaraguense",
  "NPR": "Rupia nepalesa",
  "NZD": "Dólar da Nova Zelândia",
  "OMR": "Rial omanense",
  "PAB": "Balboa panamenho",
  "PEN": "Sol peruano",
  "PGK": "Kina papuásia",
  "PHP": "Peso filipino",
  "PKR": "Rupia paquistanesa",
  "PLN": "Zloty polonês",
  "PYG": "Guarani paraguaio",
  "QAR": "Rial catariano",
  "RON": "Leu romeno",
  "RSD": "Dinar sérvio",
  "RUB": "Rublo russo",
  "RWF": "Franco ruandês",
  "SAR": "Riyal saudita",
  "SBD": "Dólar das Ilhas Salomão",
  "SCR": "Rupia seichelense",
  "SDG": "Dinar sudanês",
  "SEK": "Coroa sueca",
  "SGD": "Dólar de Cingapura",
  "SKK": "Coroa eslovaca (descontinuada)",
  "SLL": "Leone de Serra Leoa",
  "SOS": "Xelim somali",
  "SRD": "Dólar do Suriname",
  "STD": "Dobra são-tomense",
  "SVC": "Colón salvadorenho",
  "SYP": "Libra síria",
  "SZL": "Lilangeni suazi",
  "THB": "Baht tailandês",
  "TJS": "Somoni tajique",
  "TMT": "Manat turcomeno",
  "TND": "Dinar tunisiano",
  "TOP": "Pa'anga tonganesa",
  "TRY": "Lira turca",
  "TTD": "Dólar de Trinidad e Tobago",
  "TWD": "Dólar taiwanês",
  "TZS": "Xelim tanzaniano",
  "UAH": "Hryvnia ucraniano",
  "UGX": "Xelim ugandense",
  "USD": "Dólar americano",
  "UYU": "Peso uruguaio",
  "UZS": "Som uzbeque",
  "VEF": "Bolívar venezuelano (descontinuado)",
  "VND": "Dong vietnamita",
  "VUV": "Vatu de Vanuatu",
  "YER": "Rial iemenita",
  "ZAR": "Rand sul-africano",
  "ZMK": "Kwacha zambiano (descontinuado)",
  "ZWD": "Dólar do Zimbábue (descontinuado)"
}